---
title: "git_00"
author: "Candice Fallon"
date: "Year 2020"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
"You are old, father William," the young man said,  
    "And your hair has become very white;  
  And yet you incessantly stand on your head —  
    Do you think, at your age, it is right?"  
  
## Second Verse
When a friend calls to me from the road  
And slows his horse to a meaning walk,  
I don’t stand still and look around  
On all the hills I haven’t hoed,  
And shout from where I am, ‘What is it?’  
  

## Third Verse
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
  

## Last Verse
When someone's having a bad day,  
A smile could go a long way,  
So make sure to put one on  
And keep it until the day is gone.  
You don't know what this deed  
Could do for a friend in need.  
It might save them from the pain  
Of a sadness they cannot contain.  
Don't ask what a smile can do  
Because I'm sure it once helped you.  
  
Source: https://www.familyfriendpoems.com/poem/a-smile-3  
  
